4-5:	4-5.c++ words.h words.c++
	g++ -o 4-5 4-5.c++ words.h words.c++

4-6: Student_info.o grade.o median.o
	g++ -o 4-6 4-6.c++ Student_info.o grade.o median.o

Student_info.o: Student_info.c++ Student_info.h
	g++ -c Student_info.c++

grade.o: grade.c++ grade.h
	g++ -c grade.c++ grade.h

median.o: median.c++ median.h
	g++ -c median.c++ median.h
